name: FORMED
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - backcall=0.2.0
  - ca-certificates=2022.10.11
  - certifi=2022.12.7
  - decorator=5.1.1
  - executing=0.8.3
  - jedi=0.18.1
  - ld_impl_linux-64=2.38
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.3
  - openssl=1.1.1s
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.3.1
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.11.2
  - python=3.8.15
  - readline=8.2
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.40.0
  - stack_data=0.2.0
  - tk=8.6.12
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.8
  - zlib=1.2.13
  - pip:
    - ase==3.22.1
    - bottleneck==1.3.5
    - contourpy==1.0.6
    - cycler==0.11.0
    - debugpy==1.5.1
    - dpcpp-cpp-rt==2023.0.0
    - entrypoints==0.4
    - fonttools==4.38.0
    - intel-cmplr-lib-rt==2023.0.0
    - intel-cmplr-lic-rt==2023.0.0
    - intel-opencl-rt==2023.0.0
    - intel-openmp==2023.0.0
    - ipykernel==6.9.1
    - ipython==8.4.0
    - joblib==1.1.1
    - jupyter-client==7.2.2
    - jupyter-core==4.10.0
    - kiwisolver==1.4.4
    - matplotlib==3.6.2
    - matplotlib-inline==0.1.2
    - mkl==2023.0.0
    - mkl-fft==1.3.1
    - mkl-random==1.2.2
    - mkl-service==2.4.0
    - munkres==1.1.4
    - nest-asyncio==1.5.5
    - networkx==2.8.4
    - numexpr==2.8.4
    - numpy==1.22.4
    - packaging==22.0
    - pandas==1.5.2
    - pillow==9.3.0
    - ply==3.11
    - psutil==5.9.0
    - pyparsing==3.0.9
    - pyqt5-sip==12.11.0
    - python-dateutil==2.8.2
    - pytz==2022.7
    - pyzmq==23.2.0
    - qml==0.4.0.27
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - seaborn==0.12.1
    - sip==6.6.2
    - tbb==2021.8.0
    - toml==0.10.2
    - tornado==6.1
    - traitlets==5.1.1
    - xgboost==1.5.0
